# Generated by Django 3.1.7 on 2021-04-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_call_to_action_calltoaction', serialize=False, to='cms.cmsplugin')),
                ('container', models.CharField(choices=[('container', 'container'), ('container-fluid', 'container_fluid')], max_length=255, verbose_name='Container')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitel')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
